# Generated by Django 4.2.1 on 2023-07-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('C2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='command',
        ),
        migrations.AddField(
            model_name='command',
            name='description',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='command',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='command',
            name='syntax',
            field=models.CharField(default='', max_length=50),
        ),
    ]
