# Generated by Django 4.2.1 on 2023-07-29 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('C2', '0004_agenttype_agent_guid_agent_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='agent_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='C2.agenttype'),
        ),
        migrations.AlterField(
            model_name='agenttype',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
