# Generated by Django 4.2.1 on 2023-07-29 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('C2', '0005_agent_agent_type_alter_agenttype_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='agent_type',
            new_name='type',
        ),
    ]
