# Generated by Django 4.2.1 on 2023-07-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('C2', '0006_rename_agent_type_agent_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='commands',
        ),
        migrations.AddField(
            model_name='agenttype',
            name='commands',
            field=models.ManyToManyField(blank=True, to='C2.command'),
        ),
    ]
