# Generated by Django 4.2.1 on 2023-07-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('C2', '0007_remove_agent_commands_agenttype_commands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='command',
            name='syntax',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
