# Generated by Django 4.2.1 on 2023-07-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('C2', '0008_alter_command_description_alter_command_syntax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='last_online',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
